version: '3.5'
services:
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: cruddb
      POSTGRES_PASSWORD: secret
    ports:
     - '5432:5432'
    volumes:
     - ./pgdata:/var/lib/postgresql/data
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    tty: true    
    stdin_open: true  
    volumes:
      - .:/code
    depends_on:
      - db