# Generated by Django 3.2.6 on 2023-07-18 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contact_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
    ]
